In [1]:
from LogisticRegression.LogisticRegression import LogisticRegression
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# Load data
iris = datasets.load_iris()
X = iris.data[:, :2] # we only take the first two features.
y = (iris.target != 0) * 1 # convert 3 classes to binary classes

In [8]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


In [9]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(112, 2) (38, 2) (112,) (38,)


In [15]:
# Train model
model = LogisticRegression(penalty='l2', solver='lbfgs', C=1.0, max_iter=100, tol=1e-4, random_state=None)
model.fit(X_train, y_train)

LogisticRegression()

In [16]:
model.predict(X_test)

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [17]:
y_test

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [18]:
import numpy as np

np.mean(model.predict(X_test) == y_test)

1.0

In [20]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial').fit(X_train, y_train)

In [21]:
clf.predict(X_test)

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [23]:
clf.score(X_test, y_test)

1.0